# Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with the collection of mathematical functions to operate on these data structures.

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [ ]:
## create an 1D array
arr1=np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])

#reshapes into 2D (1 row and 5 columns)
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

another way to create 2D array

In [15]:
arr2=np.array([[1,2,3,4,5], [12,3,4,2,4]])

print(arr2.shape)
print(arr2)

(2, 5)
[[ 1  2  3  4  5]
 [12  3  4  2  4]]


In [17]:
#start, end (exclusive), step
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data Type: int64
Item size (in bytes): 8


In [24]:
###Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition:", arr1 + arr2)
print("Subtraction", arr1 - arr2)
print("Element-wise Multiplication", arr1 * arr2)
print("Element-wise Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Element-wise Multiplication [ 10  40  90 160 250]
Element-wise Division: [0.1 0.1 0.1 0.1 0.1]


In [27]:

arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## Universal Functions(ufuncs)

## Array slicing and indexing
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
arr[0][0]

np.int64(1)

In [33]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [36]:
## Modify array elements
arr[0][0] = 100

arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [37]:
## Statistical concepts
## to have mean of 0, standard deviation of 1
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data < 8)]

array([6, 7])

# Assignments

Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [53]:
arr1 = np.random.randint(1, 21, size=(5, 5))

arr2 = np.arange(1, 17).reshape(4,4)

#filling diagonals with some value
np.fill_diagonal(arr2, 0)

print("Array1:\n", arr1)
print("Array2:\n", arr2)

Array1:
 [[11  8  2  7 18]
 [18  2 20  7  2]
 [16  5  8 19 20]
 [ 5  2 12  6 14]
 [15 17 16  2 18]]
Array2:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [76]:
arr1 = np.arange(1,37,1).reshape(6,6)

print("Original Array\n", arr1)
print("Slice:\n", arr1[2:5, 1:4])

arr2 = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(5, 5))
print("Random Array:\n", arr2)

top_border = arr2[0:1,:]
print("top_border:", top_border)

left_border = arr2[:, 0:1]
print("left_border:", left_border)

bottom_border = arr2[-1:,:]
print("bottom_border:", bottom_border)

right_border = arr2[:, -1:]
print("right_border", right_border)

Original Array
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Slice:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Random Array:
 [[-1303374731   763365184   697189116  -337396404 -1770570911]
 [  373539608   770958830  -692978113  1626186953  1290094041]
 [   42519158 -1588008219  -381756962   299512468  1023660997]
 [ -611669887  -901752424 -1570131960  -159642157  -976011731]
 [ -239241651   213543669 -1786291413  1117156898 -2035753637]]
top_border: [[-1303374731   763365184   697189116  -337396404 -1770570911]]
left_border: [[-1303374731]
 [  373539608]
 [   42519158]
 [ -611669887]
 [ -239241651]]
bottom_border: [[ -239241651   213543669 -1786291413  1117156898 -2035753637]]
right_border [[-1770570911]
 [ 1290094041]
 [ 1023660997]
 [ -976011731]
 [-2035753637]]


Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [79]:
arr1 = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(3, 4))
arr2 = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(3, 4))

print("Array1\n", arr1)
print("Array2\n", arr2)

print("Element-wise addition:\n", arr1+arr2)
print("Element-wise subtraction:\n", arr1-arr2)
print("Element-wise multiplication:\n", arr1*arr2)
print("Element-wise division:\n", arr1 / arr2)    

Array1
 [[1392304814 1923903304 -145130743 1647421074]
 [-176294591  825233510 1563523280  347598962]
 [ 314471440  961653475 -384320969 1494338838]]
Array2
 [[-1457243318 -1522414555  1495261652 -1421002302]
 [  695855062 -1829300911  1911745451  1208090990]
 [-1945717698   517524233  1700157411   896973924]]
Element-wise addition:
 [[  -64938504   401488749  1350130909   226418772]
 [  519560471 -1004067401  -819698565  1555689952]
 [-1631246258  1479177708  1315836442 -1903654534]]
Element-wise subtraction:
 [[-1445419164  -848649437 -1640392395 -1226543920]
 [ -872149653 -1640432875  -348222171  -860492028]
 [-2034778158   444129242 -2084478380   597364914]]
Element-wise multiplication:
 [[   63938636 -1528728216 -2108437388   396410020]
 [  877767510  2146930246 -1366121744 -1881292036]
 [ -333751328 -1880554757    30199749  -206289768]]
Element-wise division:
 [[-0.95543743 -1.26371841 -0.09706043 -1.15933737]
 [-0.25334958 -0.45111961  0.81785118  0.28772581]
 [-0.16162234  1.85

In [85]:
arr = np.arange(1,17,1).reshape(4,4)

print("Column-wise sum:\n", np.sum(arr, axis=0))

print("Row-wise sum:\n", np.sum(arr, axis=1))

Column-wise sum:
 [28 32 36 40]
Row-wise sum:
 [10 26 42 58]


Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [91]:
arr = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(5, 5))

print("Array:\n", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Array:
 [[ -273107195  1274775358  1483765372  -587427976  1792185066]
 [ 1518915848   -39355780  -942609437  -118933018  -224235339]
 [-1432315315  1111759899   423525844  1453865245  2070313548]
 [-1390701724   525076888 -1867056357 -1867434649  -543360225]
 [  864644595  1006815007  1544988670  1646675906  1531230970]]
Mean: 358480048.04
Standard Deviation: 1200943334.3303328
Variance: 1.4422648922724575e+18


In [92]:
arr = np.arange(1, 10, 1).reshape(3,3)

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_data = (arr - mean) / std_dev

print(normalized_data)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [126]:
import numpy as np

# Task 1: Add a 1D array to each row of a 2D array using broadcasting
arr_3x3 = np.random.randint(1, 21, size=(3, 3))  # 3x3 array of random integers
array_1d_3 = np.random.randint(1, 21, size=(3,))  # 1D array of shape (3,)

# Broadcasting: Add the 1D array to each row of the 2D array
result_1 = arr_3x3 + array_1d_3[:, np.newaxis]  # Adding with broadcasting

print("Original 3x3 Array:\n", arr_3x3)
print("\n1D Array to add to each row:", array_1d_3)
print("\nResult after broadcasting addition:\n", result_1)

Original 3x3 Array:
 [[19  3  1]
 [16 17  1]
 [ 3 19  2]]

1D Array to add to each row: [3 3 4]

Result after broadcasting addition:
 [[22  6  4]
 [19 20  4]
 [ 7 23  6]]


In [127]:
arr_4x4 = np.random.randint(1, 21, size=(4, 4))  # 4x4 array of random integers
array_1d_4 = np.random.randint(1, 21, size=(4,))  # 1D array of shape (4,)

# Broadcasting: Subtract the 1D array from each column of the 2D array
result_2 = arr_4x4 - array_1d_4  # Broadcasting subtraction

print("\nOriginal 4x4 Array:\n", arr_4x4)
print("\n1D Array to subtract from each column:", array_1d_4)
print("\nResult after broadcasting subtraction:\n", result_2)


Original 4x4 Array:
 [[20 18 18 17]
 [12  2 18  7]
 [ 6  5 11 11]
 [ 5 10  2  3]]

1D Array to subtract from each column: [14 20  9  2]

Result after broadcasting subtraction:
 [[  6  -2   9  15]
 [ -2 -18   9   5]
 [ -8 -15   2   9]
 [ -9 -10  -7   1]]


Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [103]:
matrix = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(3,3))

inverse_matrix = np.linalg.inv(matrix)
determinant = np.linalg.det(matrix)
eigenvalues = np.linalg.eigvals(matrix)

print("Matrix:\n", matrix)
print("Inverse:\n", inverse_matrix)
print("Determinant:\n", determinant)
print("eigenvalues:\n", eigenvalues)

Matrix:
 [[-1263063781  -172636510  -499130793]
 [-1733137189  1656905145  1551829972]
 [-2116729957   -55661253 -1886776942]]
Inverse:
 [[-9.58213328e-10 -9.39177186e-11  1.76242056e-10]
 [-2.06621275e-09  4.18167803e-10  8.90532261e-10]
 [ 1.13595137e-09  9.30277982e-11 -7.53997439e-10]]
Determinant:
 3.172397558101025e+27
eigenvalues:
 [ 1.79017370e+09 -6.81042033e+08 -2.60206725e+09]


In [105]:
m1 = np.random.randint(-10, 10, size=(2,3))
m2 = np.random.randint(-10, 10, size=(3,2))

print("m1:\n", m1)
print("m2:\n", m2)

result = m1 @ m2
print("result:\n", result)


m1:
 [[ 8  4  8]
 [-9  4 -6]]
m2:
 [[  5   9]
 [  7   8]
 [ -7 -10]]
result:
 [[12 24]
 [25 11]]


Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [109]:
arr = np.arange(1, 10, 1).reshape(3,3)
print("3:3\n", arr)

arr = arr.reshape((1,9))
print("1:9\n", arr)

arr = arr.reshape((9,1))
print("9:1\n", arr)

3:3
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1:9
 [[1 2 3 4 5 6 7 8 9]]
9:1
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [117]:
arr = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(5,5))

print("Original Arr:\n", arr)

print("Flattened:\n", arr.reshape(1, arr.size))

print("Back to 5:5\n", arr.reshape(5,5))

Original Arr:
 [[  -57145250  -505759337    52301300  -986130021 -1919161908]
 [ -236214743   -28002863   223925847  1039725018   983128057]
 [ 1000837498 -1000909923  1719300341  -309486186 -1096755286]
 [  180492329  -592484875 -2025735626  1959444823  1878749847]
 [ -988222231  1493084145  2111242279  1634051157  -639133653]]
Flattened:
 [[  -57145250  -505759337    52301300  -986130021 -1919161908  -236214743
    -28002863   223925847  1039725018   983128057  1000837498 -1000909923
   1719300341  -309486186 -1096755286   180492329  -592484875 -2025735626
   1959444823  1878749847  -988222231  1493084145  2111242279  1634051157
   -639133653]]
Back to 5:5
 [[  -57145250  -505759337    52301300  -986130021 -1919161908]
 [ -236214743   -28002863   223925847  1039725018   983128057]
 [ 1000837498 -1000909923  1719300341  -309486186 -1096755286]
 [  180492329  -592484875 -2025735626  1959444823  1878749847]
 [ -988222231  1493084145  2111242279  1634051157  -639133653]]


Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [120]:
arr = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(5,5))

print("Array:\n", arr)

corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]

print("\nCorner elements:", corners)

Array:
 [[  685246136    -3612451  1114438486  -869753112 -1247612276]
 [  895643287  1604143500  -382641505 -1315419771 -1663688202]
 [ -780180504   -72486268 -1692075914   696231832   611449832]
 [  165902780 -1270884243   -37932181   -30178302  1021383135]
 [ -503282375 -1260307046 -1411395071  1731306584 -1095809188]]

Corner elements: [  685246136 -1247612276  -503282375 -1095809188]


In [121]:
arr = np.random.randint(-np.iinfo(np.int32).max, np.iinfo(np.int32).max, size=(4,4))

print("Original:\n", arr)

arr[arr > 10] = 10

print("Modified:\n", arr)

Original:
 [[ -745299680   246253995 -1732959706 -1843496699]
 [  516410467   971370548  1309869844   909821499]
 [ 1892030724 -1033650281   506196940  1570463213]
 [-1511968859 -1114560560 -1366197825 -2031869500]]
Modified:
 [[ -745299680          10 -1732959706 -1843496699]
 [         10          10          10          10]
 [         10 -1033650281          10          10]
 [-1511968859 -1114560560 -1366197825 -2031869500]]


Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [122]:
import numpy as np

# Define a structured dtype with fields 'name', 'age', and 'weight'
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

# Create a structured array with some data
arr = np.array([('Alice', 25, 55.5), 
                ('Bob', 30, 72.3), 
                ('Charlie', 22, 68.4),
                ('David', 28, 75.0)], dtype=dt)

print("Original Array:\n", arr)

# Sort the array by the 'age' field
sorted_arr = np.sort(arr, order='age')

print("\nSorted Array by Age:\n", sorted_arr)

Original Array:
 [('Alice', 25, 55.5) ('Bob', 30, 72.3) ('Charlie', 22, 68.4)
 ('David', 28, 75. )]

Sorted Array by Age:
 [('Charlie', 22, 68.4) ('Alice', 25, 55.5) ('David', 28, 75. )
 ('Bob', 30, 72.3)]


In [123]:
import numpy as np

# Define a structured dtype with fields 'x' and 'y'
dt = np.dtype([('x', 'i4'), ('y', 'i4')])

# Create a structured array with some points
arr = np.array([(1, 2), (4, 6), (7, 8), (2, 3)], dtype=dt)

print("Points:\n", arr)

# Function to compute Euclidean distance between two points
def euclidean_distance(p1, p2):
    return np.sqrt((p2['x'] - p1['x'])**2 + (p2['y'] - p1['y'])**2)

# Compute Euclidean distances between each pair of points
distances = np.zeros((len(arr), len(arr)))

for i in range(len(arr)):
    for j in range(len(arr)):
        distances[i, j] = euclidean_distance(arr[i], arr[j])

print("\nEuclidean Distances between points:\n", distances)

Points:
 [(1, 2) (4, 6) (7, 8) (2, 3)]

Euclidean Distances between points:
 [[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 3.60555128]
 [8.48528137 3.60555128 0.         7.07106781]
 [1.41421356 3.60555128 7.07106781 0.        ]]


Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [124]:
import numpy as np

# Create a 4x4 array of random integers between 1 and 20
arr = np.random.randint(1, 21, size=(4, 4))

# Create a mask for elements greater than 10
masked_arr = np.ma.masked_greater(arr, 10)

print("Original Array:\n", arr)
print("\nMasked Array (Elements greater than 10 are masked):\n", masked_arr)

# Compute the sum of the unmasked elements
sum_unmasked = masked_arr.sum()

print("\nSum of unmasked elements:", sum_unmasked)

Original Array:
 [[ 7 13 13 10]
 [11 10  7 15]
 [ 7 11 13  1]
 [ 3  3 11  9]]

Masked Array (Elements greater than 10 are masked):
 [[7 -- -- 10]
 [-- 10 7 --]
 [7 -- -- 1]
 [3 3 -- 9]]

Sum of unmasked elements: 57


In [125]:
import numpy as np

# Create a 3x3 array of random integers between 1 and 20
arr = np.random.randint(1, 21, size=(3, 3))

# Create a mask for the diagonal elements (where mask is True for diagonal)
mask = np.eye(3, dtype=bool)

# Create the masked array using the mask
masked_arr = np.ma.masked_array(arr, mask=mask)

print("Original Array:\n", arr)
print("\nMasked Array (Diagonal elements are masked):\n", masked_arr)

# Calculate the mean of the unmasked elements
mean_unmasked = masked_arr.mean()

# Replace the masked elements (diagonal) with the mean of the unmasked elements
masked_arr[mask] = mean_unmasked

print("\nMasked Array after replacing masked elements with mean:\n", masked_arr)

Original Array:
 [[ 5 12 10]
 [ 8  7 10]
 [ 8  1  9]]

Masked Array (Diagonal elements are masked):
 [[-- 12 10]
 [8 -- 10]
 [8 1 --]]

Masked Array after replacing masked elements with mean:
 [[8 12 10]
 [8 8 10]
 [8 1 8]]
